config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  root to: "scraped_links#index"
  resources :scraped_links, except: %i[new edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/individual_link.rb
class IndividualLink < ApplicationRecord
  belongs_to :scraped_link
end

app/models/scraped_link.rb
class ScrapedLink < ApplicationRecord
  has_many :individual_links, dependent: :destroy
  belongs_to :user

  enum status: { in_progress: 0, completed: 1, error: 2 }

  validates :link, presence: true

  after_initialize :set_default_status, if: :new_record?
  before_create :set_provisory_name

  private

  # Set the default status to 'in_progress' for new records
  def set_default_status
    self.status ||= :in_progress
  end

  def set_provisory_name
    self.name = extract_domain_from_link
  end

  # Extract text between "www." and the top-level domain (TLD) in the link
  def extract_domain_from_link
    # Prepend a default scheme (e.g., http) if the link lacks one
    link_with_scheme = link.start_with?('http://', 'https://') ? link : "http://#{link}"
    uri = URI(link_with_scheme)
    host = uri.host

    if host
      # Remove any subdomains and "www." if present
      host.sub(/^www\./, '').split('.').first
    else
      nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/scraped_links_controller.rb
class ScrapedLinksController < ApplicationController
  before_action :set_scraped_link, only: %i[ show destroy ]
  before_action :authenticate_user!

  # GET /scraped_links or /scraped_links.json
  def index
    scraped_links = policy_scope(ScrapedLink.order(created_at: :desc))
    @pagy, @scraped_links = pagy(scraped_links)
  end

  # GET /scraped_links/1 or /scraped_links/1.json
  def show
    authorize @scraped_link, :show?
    @pagy, @individual_links = pagy(@scraped_link.individual_links)
  end

  # POST /scraped_links or /scraped_links.json
  def create
    @scraped_link = ScrapedLink.new(scraped_link_params)

    if @scraped_link.save
      ScraperJob.perform_async(@scraped_link.id)
      redirect_to scraped_links_url, notice: "Scraped link was created and is being processed."
    else
      redirect_to scraped_links_url, alert: "There was an error scraping the url you provided"
    end
  end

  # DELETE /scraped_links/1 or /scraped_links/1.json
  def destroy
    authorize @scraped_link, :destroy?
    @scraped_link.destroy!

    respond_to do |format|
      format.html { redirect_to scraped_links_url, notice: "Scraped link was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scraped_link
      @scraped_link = ScrapedLink.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scraped_link_params
      params.require(:scraped_link).permit(:link).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/scraped_links_helper.rb
module ScrapedLinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScraper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/scraped_links/_form.html.erb
<%= form_with(model: ScrapedLink.new, url: scraped_links_path, local: true, method: :post, class: 'form-container') do |form| %>
  <div class="box is-flex is-flex-direction-row is-flex-wrap-nowrap">
    <div class="field is-flex-grow-5 mr-5">
      <div class="control">
        <%= form.text_field :link, class: 'input form-input' %>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= form.submit "Scrape", class: 'button is-info form-button' %>
      </div>
    </div>
  </div>
<% end %>

app/views/scraped_links/index.html.erb
<section class="section">
  <div class="container">
    <p class="has-text-success"><%= notice %></p>
    <p class="has-text-danger"><%= alert %></p>
    <div class="container mb-6">
      <%= render 'form'%>
    </div>
    <div class="container mb-6">
      <div class="box">
        <table class="table is-fullwidth">
          <thead>
            <tr>
              <th>Name</th>
              <th>Total</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @scraped_links.each do |scraped_link| %>
              <tr>
                <td>
                  <%= link_to scraped_link.name, scraped_link, class: 'has-text-info' %>
                </td>
                <td><%= scraped_link.total %></td>
                <td><%= scraped_link.status %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%== pagy_bulma_nav(@pagy) %>
      </div>
    </div>
  </div>
</section>

app/views/scraped_links/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mb-6 mt-6">
  <div class="box">
    <div class="content is-flex is-justify-content-center">
      <h1><%= @scraped_link.name %></h1>
    </div>
    <div>
      <%= link_to "Back to scraped links", scraped_links_path, class: 'button is-info' %>
    </div>
    <table class="table is-fullwidth">
      <tbody>
        <th><strong>Name:</strong></th>
        <th><strong>Link:</strong></th>
        <% @individual_links.each do |ind_link| %>
          <tr>
            <td><%= ind_link.name %></td>
            <td><%= ind_link.url %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%== pagy_bulma_nav(@pagy) %>
  </div>
</div>